name: custom_info_window
description: A widget based custom info window for google_maps_flutter package.
version: 1.0.1
repository: https://github.com/abhishekduhoon/custom_info_window
issue_tracker: https://github.com/abhishekduhoon/custom_info_window/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter:
    git:
      url: https://github.com/mark33699/flutter_plugins.git
      path: packages/google_maps_flutter/google_maps_flutter
      ref: 438ccabe1b74c7dfa8bc8fcc7ff91d8d97ad7421

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: